name: utopia_cms_firebase
version: 0.0.2+5
description: Utopia CMS - Firebase
homepage: https://github.com/Utopia-USS/utopia_cms

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  cloud_firestore: ^3.2.0
  utopia_cms: ^0.0.2+3
  utopia_utils: ^0.2.25
