name: utopia_cms_firebase
version: 0.1.2
description: Utopia CMS - Firebase
homepage: https://github.com/Utopia-USS/utopia_cms

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  cloud_firestore: ^4.8.5
  utopia_cms: ^0.1.2
  utopia_utils: ^0.2.25
